### ISSUE TITLE
Beautiful tutorial. One small error.

### ISSUE THREAD

**Issue by 2jacobtan** [nobrakal/alga-tutorial#1]
> ## Space is important
> 
> Your company is looking to have many users, so maybe the `ConnectU` is not very wise. In fact, adding a `(Connect (Vertex a) (Vertex b))` is not very alga-friendly. If `a` is connected to 100 people, then `Vertex a` will be 100 times in the representation!  
> On the advice of your superior, you can change it to:
> 
> ```
> handleRequestM (ConnectU a b) =
>   (>>=) (\x -> if x == a
>     then Connect (Vertex x) (Vertex b)
>     else Vertex x )
> ```
>
> The modified function will take longer to add a connection (`foldg` has a complexity of _O_(_n_)), but you will ensure that your graph will not grow too fast (if and only if there is not multiple `Vertex a` hidden in the representation).

`(>>=)` should be `(=<<)`, and the algorithm itself doesn't work on a graph like `Connect 1 2`.

```hs
[1 of 1] Compiling Alga             ( /home/jt2/repos/Haskell-Practice/algebraic-graphs-experiment/src/Alga.hs, interpreted )
Ok, one module loaded.
*Alga> main
digraph 
{
  "1"
  "2"
  "3"
  "1" -> "2"
  "1" -> "3"
}
*Alga> main2
digraph 
{
  "1"
  "2"
  "3"
  "1" -> "2"
  "1" -> "3"
  "3" -> "2"
}
```

https://github.com/2jacobtan/Haskell-Practice/blob/master/algebraic-graphs-experiment/src/Alga.hs

---

The tutorial was really nice actually. Thanks!!

**Comment by nobrakal** [comment]
Hi there,

Many thanks for your issue, it is now fixed  (I preferred to use bind fully applied to not confuse the reader). I'm glad this tutorial actually helped someone!

Have fun hacking :metal:

**Comment by 2jacobtan** [comment]
Thanks for the response!

Though, the alternate implementation with `>>=` still has a different behaviour than the original implementation.

I.e. it creates more edges than intended.

```hs
-- original implementation
handleRequestM (ConnectU 1 3) (Connect 1 2) ==
digraph 
{
  "1"
  "2"
  "3"
  "1" -> "2"
  "1" -> "3"
}

-- alternate implementation
handleRequestM (ConnectU 1 3) (Connect 1 2) ==
digraph 
{
  "1"
  "2"
  "3"
  "1" -> "2"
  "1" -> "3"
  "3" -> "2"  -- not intended
}
```

**Comment by nobrakal** [comment]
Oops, this second implementation was obviously an error made to see you were following...
Thanks for reporting this, it was totally faulty! I removed the concerned section as it doesn't seem fixable.

**Comment by 2jacobtan** [comment]
Hehe, yes I was paying attention because it was a good tutorial :)
